---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
      - name: project-container
        image: yang97docker/cicd-project:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-project
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31500
